#!/bin/bash
set -e

function check_command() {
  local c=$1
  if ! type -p ${c} >/dev/null; then
    echo "${c} not found on the system" >&2
    exit 1
  fi
}

function check() {
  local required_command=(fzf ghq)
  for c in ${required_command[@]}; do
    check_command(${c})
  done
}

function run() {
  local cc="cat"
  if ! type -p "bat" >/dev/null; then
    cc="bat"
  fi
  repo_path=`ghq list --full-path | fzf --reverse --preview "${cc} {1}/README.md"`
  \cd ${repo_path}
}

check()
run()
