#!/bin/bash
set -e

use_tmux=false
new_window=false

[ -n "${TMUX}" ] && use_tmux=true
while [[ $# -gt 0 ]]; do
  case "$1" in
  -nw)
    $use_tmux && new_window=true
    shift
    ;;
  *)
    echo "Unknown argument: $1"
    exit 1
    ;;
  esac
done

function exist_command() {
  local c=$1
  if ! type -p ${c} >/dev/null; then
    return 1
  fi
  return 0
}

function check() {
  local required_command=(fzf ghq)
  for c in ${required_command[@]}; do
    if ! exist_command "${c}"; then
      echo "${c} not found on the system" >&2
      exit 1
    fi
  done
}

function choose() {
  local cc="cat"
  if exist_command "bat"; then
    cc="bat"
  fi
  ghq list --full-path | fzf --reverse --preview "${cc} {1}/README.md"
}

function tmux_new_window() {
  local dir=$1
  repo=$(basename "${dir}")
  tmux new-window -n "${repo}" -c "${dir}"
}

function tmux_op() {
  local dir=$1
  repo=$(basename "${dir}")
  $new_window && tmux new-window -n "${repo}" -c "${dir}" && return
  tmux rename-window "${repo}"
}

check
selected="$(choose)"
[ -n "${selected}" ] || exit 1
repo=$(basename "${selected}")
if $new_window; then
  tmux new-window -n "${repo}" -c "${selected}"
  exit 0
fi
\cd ${selected}
$use_tmux && tmux rename-window $repo
$SHELL
