#!/bin/bash
set -e

function exist_command() {
  local c=$1
  if ! type -p ${c} >/dev/null; then
    return 1
  fi
  return 0
}

function check() {
  local required_command=(fzf ghq)
  for c in ${required_command[@]}; do
    if ! exist_command "${c}"; then
      echo "${c} not found on the system" >&2
      exit 1
    fi
  done
}

function choose() {
  local cc="cat"
  if exist_command "bat"; then
    cc="bat"
  fi
  ghq list --full-path | fzf --reverse --preview "${cc} {1}/README.md"
}

check
selected="$(choose)"
[ -n "${selected}" ] || exit 1
\cd ${selected}
$SHELL
